# Deploy to Azure Kubernetes Service
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:

  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'a2fd800b-c2eb-42dc-bee0-968108d219d8'
  imageRepository: 'josephmkureekattusampleapiapp'
  containerRegistry: 'testreg22.azurecr.io'
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildId)'
  imagePullSecret: 'testreg2219566f44-auth'
  CONTAINER-REPO: 'testreg22.azurecr.io'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'


stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)                
    - upload: manifests
      artifact: manifests
    - task: CopyFiles@2
      inputs:
        contents: $(build.sourcesDirectory)/kubedeployconfigs/*.*
        targetFolder: $(build.artifactStagingDirectory)
    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: $(build.artifactStagingDirectory)
        artifactName: drop

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build

  jobs:
  - deployment: Deploy
    displayName: Deploy
    pool:
      vmImage: $(vmImageName)
    environment: 'josephmkureekattusampleapiapp-2091.default'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: KubernetesManifest@0
            displayName: Create imagePullSecret
            inputs:
              action: createSecret
              secretName: $(imagePullSecret)
              dockerRegistryEndpoint: $(dockerRegistryServiceConnection)          
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                sed ''s/__CONTAINER-REPO__/$(containerRegistry)/''  $(Pipeline.Workspace)/drop/kubedeployconfigs/kubedeployconfigs.yaml      
                sed ''s/__imageRepository__/$(imageRepository)/''  $(Pipeline.Workspace)/drop/kubedeployconfigs/kubedeployconfigs.yaml      
                sed ''s/__tag__/$(tag)/''  $(Pipeline.Workspace)/drop/kubedeployconfigs/kubedeployconfigs.yaml
          - task: KubernetesManifest@0
            displayName: Deploy to Kubernetes cluster
            inputs:
              action: deploy
              manifests: |
                $(Pipeline.Workspace)/drop/kubedeployconfigs/kubedeployconfigs.yaml
              imagePullSecrets: |
                $(imagePullSecret)
              containers: |
                $(imageRepository):$(tag)

