---
steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - gcr.io/the-helix-316011/sampleapiapp:latest
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/the-helix-316011/sampleapiapp:latest
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - sampleapiappcloudrun
      - --image
      - gcr.io/the-helix-316011/sampleapiapp:latest
      - --region
      - us-central1
    images:
      - gcr.io/the-helix-316011/sampleapiapp:latest
  - name: gcr.io/cloud-builders/gke-deploy
    args:
      - run
      - --filename=kubedeployconfigs
      - --location=europe-central2
      - --cluster=autopilot-cluster-1
