steps:
...
# deploy container image to GKE
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=/kubedeployconfigs
  - --location=europe-central2
  - --cluster=autopilot-cluster-1
