---
steps:
  - name: gcr.io/cloud-builders/docker
   args:
     - build
      - -t
      - gcr.io/the-helix-316011/sampleapiapp:latest
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/the-helix-316011/sampleapiapp:latest
#  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
#    entrypoint: gcloud
#    args:
#      - run
#      - deploy
3      - sampleapiappcloudrun
#      - --image
#      - gcr.io/the-helix-316011/sampleapiapp:latest
#      - --region
#      - us-central1
  - name: bash
    script: |
         sed -i -e 's+__CONTAINER-REPO__+gcr.io/the-helix-316011+'  kubedeployconfigs/kubedeployconfigs.yaml -e ''s/__imageRepository__/sampleapiapp/''  kubedeployconfigs/kubedeployconfigs.yaml -e   ''s/__tag__/latest/''  kubedeployconfigs/kubedeployconfigs.yaml  -e ''s/__DbConnection__/"Server=tcp:samplejsptest.database.windows.net,1433;Initial Catalog=sampleapidb;Persist Security Info=False;User ID=jsp;Password=Password@123;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"/''  kubedeployconfigs/kubedeployconfigs.yaml
  - name: gcr.io/cloud-builders/gke-deploy
    args:
      - run
      - --filename=kubedeployconfigs
      - --location=europe-central2
      - --cluster=autopilot-cluster-1
    env:
    - 'CONTAINER_REPO=gcr.io/the-helix-316011'
options:
  logging: CLOUD_LOGGING_ONLY
