---
steps:
#  - name: gcr.io/cloud-builders/docker
#   args:
#     - build
#      - -t
#      - gcr.io/the-helix-316011/sampleapiapp:latest
#      - .
#  - name: gcr.io/cloud-builders/docker
#    args:
#      - push
#      - gcr.io/the-helix-316011/sampleapiapp:latest
#  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
#    entrypoint: gcloud
#    args:
#      - run
#      - deploy
#      - sampleapiappcloudrun
#      - --image
#      - gcr.io/the-helix-316011/sampleapiapp:latest
#      - --region
#      - us-central1
  - name: bash
    script: |
         sed -i -e ''s/__CONTAINER-REPO__/sdfsdf/''  /home/vsts/work/1/drop/kubedeployconfigs/kubedeployconfigs.yaml -e ''s/__imageRepository__/sampleapiapp/''  /home/vsts/work/1/drop/kubedeployconfigs/kubedeployconfigs.yaml -e   ''s/__tag__/latest/''  /home/vsts/work/1/drop/kubedeployconfigs/kubedeployconfigs.yaml
  - name: gcr.io/cloud-builders/gke-deploy
    args:
      - run
      - --filename=kubedeployconfigs
      - --location=europe-central2
      - --cluster=autopilot-cluster-1
    env:
    - 'CONTAINER_REPO=gcr.io/the-helix-316011'
options:
  logging: CLOUD_LOGGING_ONLY
