---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "sampleapp2"
  namespace: "default"
  labels:
    app: "sampleapp2"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "sampleapp2"
  template:
    metadata:
      labels:
        app: "sampleapp2"
    spec:
      containers:
      - name: "sampleapiapp"
        image: "gcr.io/the-helix-316011/sampleapiapp:latest"
---
apiVersion: "autoscaling/v2"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "sampleapp2-hpa-ardv"
  namespace: "default"
  labels:
    app: "sampleapp2"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "sampleapp2"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      target:
        type: "Utilization"
        averageUtilization: 80