---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "sampleapp2"
  namespace: "default"
  labels:
    app: "sampleapp2"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "sampleapp2"
  template:
    metadata:
      labels:
        app: "sampleapp2"
    spec:
      containers:
      - name: "sampleapiapp"
        image: "gcr.io/the-helix-316011/sampleapiapp:latest"
---
apiVersion: v1
kind: Service
metadata:
  name: sampleapp2-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: sampleapp2
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sampleapp2-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: sampleapp2-example
  rules:
  - http:
      paths:
      - path: /testpath
        pathType: Prefix
        backend:
          service:
            name: sampleapp2-service
            port:
              number: 80
status:
  loadBalancer: {}
---
apiVersion: "autoscaling/v2"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "sampleapp2-hpa-ardv"
  namespace: "default"
  labels:
    app: "sampleapp2"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "sampleapp2"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      target:
        type: "Utilization"
        averageUtilization: 80